--XTABLAS

DROP TABLE Apuestas CASCADE CONSTRAINTS;
DROP TABLE CambioFichas CASCADE CONSTRAINTS;
DROP TABLE Mesas CASCADE CONSTRAINTS;
DROP TABLE Juegos CASCADE CONSTRAINTS;
DROP TABLE Dealers CASCADE CONSTRAINTS;
DROP TABLE Cajeros CASCADE CONSTRAINTS;
DROP TABLE Empleados CASCADE CONSTRAINTS;
DROP TABLE UsuariosFrecuentes_Beneficios CASCADE CONSTRAINTS;
DROP TABLE Beneficios CASCADE CONSTRAINTS;
DROP TABLE UsuariosInvitados CASCADE CONSTRAINTS;
DROP TABLE UsuariosFrecuentes CASCADE CONSTRAINTS;
DROP TABLE Usuarios CASCADE CONSTRAINTS;