--Correcion XCRUD

DROP PACKAGE PCK_MANTENIMIENTO;
DROP PACKAGE PCK_USUARIOS_FUNC;
DROP PACKAGE PCK_TRANSACCIONES;
DROP PACKAGE PCK_APUESTAS;
DROP PACKAGE PCK_EXCEPCIONES;
DROP PACKAGE PKG_TRG_PROMOVER_HELPER;